### ISSUE TITLE
tutorial2: Inference output data

### ISSUE THREAD

**Issue by hugokitano** [clara-parabricks/AtacWorks#188]
Is it possible that we can download the outputs of the Tutorial 2 output? I'd like to take a look at them before I start running a GPU. Thanks!

```
NK_inferred.track.bedGraph
NK_inferred.track.bw
NK_inferred.peaks.bedGraph.
NK_inferred.peaks.bw
```

Hugo

**Comment by avantikalal** [comment]
These files are available here: 
https://atacworks-paper.s3.us-east-2.amazonaws.com/dsc_atac_blood_cell_denoising_experiments/50_cells/output/NK_inf.wg.peaks.bw
https://atacworks-paper.s3.us-east-2.amazonaws.com/dsc_atac_blood_cell_denoising_experiments/50_cells/output/NK_inf.wg.track.bw

However, the peaks.bw file here was created using the alternate inference command in Appendix 1 of the tutorial. So it contains the probability of each base being part of a peak. You can use it to generate peak calls with different probability thresholds using MACS2 as described in the tutorial.
