### ISSUE TITLE
mouse reference

### ISSUE THREAD

**Issue by elffairy90** [clara-parabricks/AtacWorks#239]
Hi, 

Just a quick question, where can I find the reference genome for mice (mm10) that's equivalent to hg19.auto.sizes file?
Best regards, 
Jenny

**Comment by avantikalal** [comment]
Hi @elffairy90 , you can find the full chromosome sizes file for mm10 here: https://github.com/igvteam/igv/blob/master/genomes/sizes/mm10.chrom.sizes

Simply take the rows corresponding to autosomes (chr1-19).

**Comment by elffairy90** [comment]
Hi Avantikalal, 

Thank you very much!!! This is super helpful!
