### ISSUE TITLE
mouse reference genome

### ISSUE THREAD

**Issue by elffairy90** [clara-parabricks/AtacWorks#243]
Hi, 
I thought I asked this before, but I don't seem to find it in the thread anymore, and I wasn't sure if it has been answered. So I thought I just post it again. 

Was there a mouse genome for mice samples? I dont remember seeing it in the folder.
So in other words, what should I in the case of the mice samples?

Best regards, 
Jenny

**Comment by avantikalal** [comment]
https://github.com/clara-parabricks/AtacWorks/issues/239
