### ISSUE TITLE
Dynamic downsampling of coverage track

### ISSUE THREAD

**Issue by avantikalal** [clara-parabricks/AtacWorks#4]
- test initial code (https://github.com/clara-genomics/AtacWorks/commit/eebbae33391bceafc95f99a0a2dbea5dcf9f66fc)
- verify improvement in results

**Comment by ntadimeti** [comment]
@avantikalal , @tijyojwad  -- need your input in knowing if this issue is relevant/important ?

**Comment by avantikalal** [comment]
Initial results showed this did not improve performance. Not worth pursuing at the moment as >5x resampling of training data doesn't noticeably improve performance in our experiments.
